trailingComma: "es5"
semi: true 
arrowParens: "always"
bracketSpacing: true
htmlWhitespaceSensitivity: "css"
bracketSameLine: true 
proseWrap: "preserve" 
quoteProps: "as-needed"
jsxSingleQuote: true
singleAttributePerLine: true
singleQuote: true
tabWidth: 2
useTabs: false
experimentalTernaries: true
